import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ReduxProvider } from "@/providers/ReduxProvider";
import AppWalletProvider from "../components/AppWalletProvider";
import { Toaster } from "react-hot-toast";
import { Toaster as ToasterAll } from "@/components/ui/toaster";
import ClientSide from "@/components/ClientSide";
import { CivicAuthProvider } from "@civic/auth-web3/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppWalletProvider>
          <ReduxProvider>
            <ClientSide>{children}</ClientSide>
            <ToasterAll />
            <Toaster position="top-center" />
          </ReduxProvider>
        </AppWalletProvider>
      </body>
    </html>
  );
}
